pipeline{
    agent any
    tools{
        maven 'maven'
        jdk 'jdk-16.0.1'
    }
    stages{
        stage("Initialize"){
            steps{
                sh ''' 
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                '''
            }
        }
        stage("clean up"){
            steps{
                deleteDir()
            }
        }
        stage("clone repo" ){
            steps{
                sh "git clone https://github.com/pancho17/simple-java-maven-app2.git"
            }
        }
        stage("build"){
            steps{
                dir("simple-java-maven-app2"){
                    sh "mvn clean install"
                }
            }
        }
        stage("test"){
            steps{
                dir("simple-java-maven-app2"){
                    sh "mvn test"
                }
            }
        }
        stage(){
            steps{
                echo 'Job Complete!'
            }
        }
    }
}